id: PE15078E4
initial_creation_type: ocr
source_metadata:
  volumes:
    071047e7bcbd4f36bc3feb3f0e411065:
      base_file: v064.txt
      image_group_id: I1PD95909
      title: སྙིང་པོ་ངེས་པར་བསྡུ་བ།
      total_pages: 1902
      volume_number: 64
